import { useMigrations } from 'drizzle-orm/expo-sqlite/migrator';
// Generated by `npm run db:generate`. Committed so every install runs the same
// schema history rather than creating tables ad hoc at runtime.
import migrations from '../../../drizzle/migrations';
import { db } from './client';

export interface MigrationState {
  readonly success: boolean;
  readonly error: Error | undefined;
}

export function useDatabaseMigrations(): MigrationState {
  const { success, error } = useMigrations(db, migrations);
  return { success, error };
}
